version: '3'
# usage:
# (sudo) docker-compose up
# (sudo) docker-compose down
services:
  nipttool-web:
    container_name: niptool-web
    build:
      context: NIPTool
      dockerfile: Dockerfile
    volumes:
      - /home/worker/app/NIPTool/NIPT_RESULTS:/var/NIPT_RESULTS
    environment:
      NIPT_CONFIG: '/home/worker/app/NIPTool/config.py'
    networks:
      - niptool-net
    depends_on:
      - mongo
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: nipt run --host 0.0.0.0

  mongo:
    networks:
      - niptool-net
    image: mongo
    ports:
      - '27017:27017'
    expose:
      - '27017'

  restore:
    networks:
      - niptool-net
    image: mongo
    volumes:
      - ./dump:/var/dump
    links:
      - mongo:mongo
    command: mongorestore --host mongo:27017 /var/dump/

networks:
  niptool-net:
    driver: bridge
    ipam:
      driver: default

